USE OPERATION;
SELECT * FROM COURSE;

SELECT * FROM STUDENT;

#COLUMNS FROM DIFFERENT TABLES WITH SAME DATA TYPES
SELECT COURSE_ID, COURSE_NAME FROM COURSE
UNION
SELECT STUDENT_ID, STUDENT_NAME FROM STUDENT;

#COLUMNS FROM DIFFERENT TABLES WITH SAME DATA TYPES
SELECT COURSE_ID, COURSE_NAME FROM COURSE
UNION
SELECT STUDENT_ID, STUDENT_NAME FROM STUDENT;

#WITH DIFFERENT DATA TYPES, IT COMBINES DATA
SELECT COURSE_DESC, COURSE_NAME FROM COURSE
UNION
SELECT STUDENT_ID, STUDENT_NAME FROM STUDENT;

#UNION TRIES TO REMOVE DUPLICATE RECORDS, GIVES UNIQUE RESPONSES

SELECT COURSE_DESC, COURSE_NAME FROM COURSE
UNION ALL
SELECT STUDENT_ID, STUDENT_NAME FROM STUDENT;

#UNION ALL GIVES ALL RECORDS INCLUDING DUPLICATES
