#COMMON TABLE EXPRESSION (CTE)

USE OPERATION;

SELECT * FROM COURSE WHERE COURSE_ID in (101,102,106,105,110,113);

WITH SAMPLE_STUDENTS AS (
SELECT * FROM COURSE WHERE COURSE_ID in (101,102,106))
SELECT * FROM SAMPLE_STUDENTS WHERE COURSE_name = 'analytics'


WITH OUTCOME_LJ AS (
SELECT C.COURSE_ID, S.STUDENT_COURSE_ID, C.COURSE_NAME, C.COURSE_DESC, S.STUDENT_ID, S.STUDENT_NAME FROM COURSE C
left JOIN
STUDENT S ON C.COURSE_ID = S.STUDENT_COURSE_ID)
SELECT * FROM OUTCOME_LJ WHERE COURSE_ID = 101;

WITH CTE_T1 AS (
SELECT 1 AS COL1, 2 AS COL2
UNION ALL
SELECT 3,4)
SELECT COL1 FROM CTE_T1;

WITH RECURSIVE CTE_RECURSIVE(N) AS (
SELECT 1 UNION ALL SELECT N+1 FROM CTE_RECURSIVE WHERE N < 5)
SELECT * FROM CTE_RECURSIVE;

WITH RECURSIVE CTE AS (
SELECT 1 AS N, 1 AS P, -1 AS Q
UNION ALL
SELECT N+1, P+1, Q+2 FROM CTE WHERE N < 5)
SELECT * FROM CTE;

SELECT 1 AS N, 1 AS P, -1 AS Q;
