# 6 types of trigger
#insert - before / after 
#update - before / after
#delete - before  after

# triggers automatically

CREATE DATABASE INEURON_TRIGGERS;
USE INEURON_TRIGGERS;

DROP TABLE COURSE;

CREATE TABLE COURSE(
COURSE_ID INT,
COURSE_DESC VARCHAR(50),
COURSE_MENTOR VARCHAR(50),
COURSE_PRICE INT,
COURSE_DISCOUNT INT,
COURSE_DATE DATE);

CREATE TABLE COURSE_USER(
COURSE_ID INT,
COURSE_DESC VARCHAR(50),
COURSE_MENTOR VARCHAR(50),
COURSE_PRICE INT,
COURSE_DISCOUNT INT,
COURSE_DATE DATE,
USER_INFO VARCHAR(30));

CREATE TABLE COURSE_UPDATE(
COURSE_MENTOR_UPDATE VARCHAR(50),
COURSE_PRICE_UPDATE INT,
COURSE_DISCOUNT_UPDATE INT);

SELECT * FROM COURSE_UPDATE;

#-----------------------------------------------
#--- BEFORE INSERT
#-----------------------------------------------

DELIMITER //
CREATE TRIGGER COURSE_BEFORE_INSERT
BEFORE INSERT
ON COURSE FOR EACH ROW
BEGIN
	SET NEW.COURSE_DATE = SYSDATE();
END; //

DELIMITER //
CREATE TRIGGER COURSE_BEFORE_INSERT12
BEFORE INSERT
ON COURSE_USER FOR EACH ROW
BEGIN
    DECLARE USER_VAL VARCHAR(30);
	SET NEW.COURSE_DATE = SYSDATE();
    SELECT USER() INTO USER_VAL;
    SET NEW.USER_INFO = USER_VAL;
    INSERT INTO REF_TABLE VALUES (SYSDATE(),USER_VAL);
END; //

CREATE TABLE REF_TABLE(
COURSE_DATE DATE,
USER_INFO VARCHAR(30));

SELECT * FROM COURSE;

insert into course (COURSE_ID, COURSE_DESC, COURSE_MENTOR, COURSE_PRICE, COURSE_DISCOUNT) values (1001,"fsda","sagar",4000,10)

insert into course_USER (COURSE_ID, COURSE_DESC, COURSE_MENTOR, COURSE_PRICE, COURSE_DISCOUNT) values (1001,"fsda","sagar",4000,10)

SELECT * FROM course_USER;
SELECT * FROM REF_TABLE;

#-----------------------------------------------

CREATE TABLE TEST1(
C1 VARCHAR(50),
C2 DATE,
C3 INT)

CREATE TABLE TEST2(
C1 VARCHAR(50),
C2 DATE,
C3 INT)

CREATE TABLE TEST3(
C1 VARCHAR(50),
C2 DATE,
C3 INT)

DROP TRIGGER UPDATE_TEST2_TEST3

DELIMITER //
CREATE TRIGGER UPDATE_TEST2_TEST3
BEFORE INSERT
ON TEST1 FOR EACH ROW
BEGIN
    INSERT INTO TEST2(C1,C2,C3) VALUES ("Name in Test2",SYSDATE(),101);
    INSERT INTO TEST3(C1,C2,C3) VALUES ("Name in Test3",SYSDATE(),201);
END; //

SELECT * FROM TEST1;
SELECT * FROM TEST2;
SELECT * FROM TEST3;

INSERT INTO TEST1 (c1,c2,c3) VALUES ("Name in Test1",SYSDATE(),001);

#-----------------------------------------------
#--- AFTER INSERT
#-----------------------------------------------

DELIMITER //
CREATE TRIGGER AFTER_TEST2_TEST3
AFTER INSERT
ON TEST1 FOR EACH ROW
BEGIN
    UPDATE TEST2 SET C1= "AFTER INSERT IN TEST1" WHERE C3=101;
    DELETE FROM TEST3 WHERE C3=201;
END; //

INSERT INTO TEST1 (c1,c2,c3) VALUES ("Name in Test1",SYSDATE(),001);

SELECT * FROM TEST1;
SELECT * FROM TEST2;
SELECT * FROM TEST3;

#UPDATE AND INSERT OPERATIONS PERFORMED IN T2 AND T3 TABLE, WHEN WE INSERTED A RECORD IN T1


#-----------------------------------------------
#--- AFTER DELETE
#-----------------------------------------------

DROP TRIGGER AFTER_DELETE_TEST2_TEST3

DELIMITER //
CREATE TRIGGER AFTER_DELETE_TEST2_TEST3
AFTER DELETE
ON TEST1 FOR EACH ROW
BEGIN
    UPDATE TEST2 SET C1= "AFTER DELETE IN T2" WHERE C3=101;
    INSERT INTO TEST3 VALUES ("DELETED ROW IN T1",SYSDATE(),301);
END; //

DELETE FROM TEST1 WHERE C3 = 1;

SELECT * FROM TEST1;
SELECT * FROM TEST2;
SELECT * FROM TEST3;

#-----------------------------------------------
#--- BEFORE DELETE
#-----------------------------------------------

DROP TRIGGER BEFORE_DELETE_TEST2_TEST3

DELIMITER //
CREATE TRIGGER BEFORE_DELETE_TEST2_TEST3
BEFORE DELETE
ON TEST1 FOR EACH ROW
BEGIN
    UPDATE TEST2 SET C1= "BEFORE DELETE IN T1" WHERE C3=101;
    INSERT INTO TEST3 VALUES ("BEFORE DELETE ROW IN T1",SYSDATE(),301);
END; //

SELECT * FROM TEST1;
SELECT * FROM TEST2;
SELECT * FROM TEST3;

INSERT INTO TEST1 VALUES ("BEFORE DELETE ROW IN T1",SYSDATE(),101);
INSERT INTO TEST1 VALUES ("BEFORE DELETE ROW IN T1",SYSDATE(),102);

DELETE FROM TEST1 WHERE C3 = 102;


#------------------------

CREATE TABLE TEST11(
C1 VARCHAR(50),
C2 DATE,
C3 INT)

CREATE TABLE TEST111(
C1 VARCHAR(50),
C2 DATE,
C3 INT)

CREATE TABLE TEST12(
C1 VARCHAR(50),
C2 DATE,
C3 INT)


DELIMITER //
CREATE TRIGGER BEFORE_DELETE_TEST11112
BEFORE DELETE
ON TEST111 FOR EACH ROW
BEGIN
    INSERT INTO TEST12 VALUES (OLD.C1,OLD.C2,OLD.C3);
END; //

SELECT * FROM TEST111;
SELECT * FROM TEST12;

INSERT INTO TEST111 VALUES ("DEF",SYSDATE(),12345);

DELETE FROM TEST111 WHERE C3 = 12345;

#-----------------------------------------------
#--- AFTER UPDATE
#-----------------------------------------------

CREATE TABLE UPDATE_TEST1(
C1 VARCHAR(50),
C2 DATE,
C3 INT)

CREATE TABLE UPDATE_TEST2(
C1 VARCHAR(50),
C2 DATE,
C3 INT)

DROP TRIGGER AFTER_UPDATE_TEST2_TEST3
DROP TRIGGER AFTER_UPDATE_TEST2

DELIMITER //
CREATE TRIGGER AFTER_UPDATE_TEST2
AFTER UPDATE
ON UPDATE_TEST1 FOR EACH ROW
BEGIN
    INSERT INTO UPDATE_TEST2 VALUES ("T2",SYSDATE(),201);
END; //

SELECT * FROM UPDATE_TEST1;
SELECT * FROM UPDATE_TEST2;

INSERT INTO UPDATE_TEST1 VALUES ("ABC",SYSDATE(),12345);

UPDATE UPDATE_TEST1 SET C1 = "ABC" WHERE C1 = "abc";

TRUNCATE UPDATE_TEST2;

#-----------------------------------------------
#--- BEFORE UPDATE
#-----------------------------------------------

DELIMTER //
CREATE TRIGGER BEFORE_UPDATE_TEST2
BEFORE UPDATE
ON UPDATE_TEST1 FOR EACH ROW
BEGIN
    INSERT INTO UPDATE_TEST2 VALUES (NEW.C1,NEW.C2,NEW.C3);
END; //
