USE INEURON_PARTITION;
SELECT * FROM INEURON_COURSE;

SELECT *, CASE 
	WHEN  COURSE_NAME = "MACHINE LEARNING" THEN "THIS IS MY BATCH"
	ELSE "THIS IS NOT YOUR BATCH"
END AS STATEMENT
FROM INEURON_COURSE

SELECT *, CASE
	WHEN  LENGTH(COURSE_NAME) = 4 THEN "LENGTH 4"
    WHEN  LENGTH(COURSE_NAME) = 2 THEN "LENGTH 2"
	ELSE "UNKNOWN"
END AS STATEMENT
FROM INEURON_COURSE

UPDATE INEURON_COURSE SET COURSE_DESCR = CASE
	WHEN  COURSE_NAME = "MACHINE LEARNING" THEN "THIS IS ML BATCH"
    WHEN  COURSE_NAME = "AIOPS" THEN "THIS IS AIPOS BATCH"
    WHEN  COURSE_NAME = "BIG DATA" THEN "THIS IS BIG DATA BATCH"
    WHEN  COURSE_NAME = "FSDS" THEN "THIS IS FSDS BATCH"
    WHEN  COURSE_NAME = "FSDA" THEN "THIS IS FSDA BATCH"
    WHEN  COURSE_NAME = "JAVA" THEN "THIS IS JAVA BATCH"
    WHEN  COURSE_NAME = "DL" THEN "THIS IS DL BATCH"
    WHEN  COURSE_NAME = "DATA ANALYTICS" THEN "THIS IS DA BATCH"
	ELSE "UNKNOWN"
    END,
    COURSE_FEE = CASE
	WHEN  COURSE_NAME = "MACHINE LEARNING" THEN 3540
    WHEN  COURSE_NAME = "AIOPS" THEN 3600
    WHEN  COURSE_NAME = "BIG DATA" THEN 3200
    WHEN  COURSE_NAME = "FSDS" THEN 4500
    WHEN  COURSE_NAME = "FSDA" THEN 4000
    WHEN  COURSE_NAME = "JAVA" THEN 3000
    WHEN  COURSE_NAME = "DL" THEN 2500
    WHEN  COURSE_NAME = "DATA ANALYTICS" THEN 3400
	ELSE 0
    END,
    COURSE_TITLE = CASE
	WHEN  COURSE_NAME = "MACHINE LEARNING" THEN "ML"
    WHEN  COURSE_NAME = "AIOPS" THEN "AIOPS"
    WHEN  COURSE_NAME = "BIG DATA" THEN "BG"
    WHEN  COURSE_NAME = "FSDS" THEN "FSDS"
    WHEN  COURSE_NAME = "FSDA" THEN "FSDA"
    WHEN  COURSE_NAME = "JAVA" THEN "JAVA"
    WHEN  COURSE_NAME = "DL" THEN "DL"
    WHEN  COURSE_NAME = "DATA ANALYTICS" THEN "DA"
	ELSE "UNKNOWN"
END,
    COURSE_MENTOR = CASE
	WHEN  COURSE_NAME = "MACHINE LEARNING" THEN "SUDHANSHU"
    WHEN  COURSE_NAME = "AIOPS" THEN "KRISH"
    WHEN  COURSE_NAME = "BIG DATA" THEN "KRISH"
    WHEN  COURSE_NAME = "FSDS" THEN "AMIT"
    WHEN  COURSE_NAME = "FSDA" THEN "ABHIJEET"
    WHEN  COURSE_NAME = "JAVA" THEN "ABHIJEET"
    WHEN  COURSE_NAME = "DL" THEN "KRISH"
    WHEN  COURSE_NAME = "DATA ANALYTICS" THEN "JEETU"
	ELSE "UNKNOWN"
END

SELECT * FROM INEURON_COURSE;
