USE INEURON_FSDA;
SELECT * FROM BANK_DETAILS;

# CREATING VIEWS 

CREATE VIEW BANK_VIEW AS
SELECT AGE, JOB, MARITAL, BALANCE, EDUCATION FROM 
bank_details;

SELECT * FROM bank_view WHERE AGE < 45;

# CREATING PROCEDURE AND CALLING A VIEW
DELIMITER &&
CREATE PROCEDURE SELECT_JOB_EDU_MULTI_PARAM_WITH_VIEWS(IN Age_ INT(30),IN educ varchar(30))
BEGIN
select * from BANK_VIEW where AGE < Age_ and education = educ;
END &&

# CALLING PROCEDURE

CALL SELECT_JOB_EDU_MULTI_PARAM_WITH_VIEWS(45,'primary');
# WITH EDUCATION IN UPPER CASE
CALL SELECT_JOB_EDU_MULTI_PARAM_WITH_VIEWS(45,'PRIMARY');
